### ISSUE TITLE
Colormap Link is Broken

### ISSUE THREAD

**Issue by clkruse** [carbonplan/colormaps#9]
👋
Stumbled upon this repo after seeing a shoutout to carbonplan styles in [this notebook](https://github.com/carbonplan/trace/blob/main/notebooks/lidar_blog_sample_notebook.ipynb). I noticed the link in the repo sidebar and in the readme point to https://design.carbonplan.org/colormaps, but it 404s. Is the correct link https://carbonplan.org/design/colormaps? 

Love your work!

**Comment by freeman-lab** [comment]
Oops, thanks so much for flagging! Fixed!
